Controllers/AnuncioController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using BlackImoveisII.Models;
using Microsoft.AspNetCore.Http;

namespace BlackImoveisII.Controllers
{
    public class AnuncioController : Controller
    {
        public IActionResult Cadastro()
        {
            /*if (HttpContext.Session.GetInt32("idUsuario") == null)
            {
                return RedirectToAction("Login", "Usuario");
            }*/
            return View();
        }
        [HttpPost]
        public IActionResult Cadastro(Anuncio novoAnuncio)
        {
            AnuncioBanco anun =  new AnuncioBanco();
            anun.Insert(novoAnuncio);
            ViewBag.Mensagem = "Cadastro concluído com sucesso!";
            return View();
        }
        public IActionResult Lista()
        {
            /*if (HttpContext.Session.GetInt32("idUsuario") == null)
            {
                return RedirectToAction("Login", "Usuario");
            }*/
            AnuncioBanco anun = new AnuncioBanco();
            List<Anuncio> lista = anun.Query();
            return View(lista);
        }
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Login", "Usuario");
        }
        /*public IActionResult Vitrine()
        {
            PacoteBanco pack = new PacoteBanco();
            List<Pacote> lista = pack.Query();
            return View(lista);
        }*/
    }
}

Controllers/MensagemController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using BlackImoveisII.Models;
using Microsoft.AspNetCore.Http;

namespace BlackImoveisII.Controllers
{
    public class MensagemController : Controller
    {
        public IActionResult FaleConosco()
        {
            return View();
        }
        [HttpPost]
        public IActionResult FaleConosco(Mensagem novaMensagem)
        {
            MensagemBanco mens =  new MensagemBanco();
            mens.Insert(novaMensagem);
            ViewBag.Mensagem = "Mensagem enviada com sucesso!";
            return View();
        }
        public IActionResult Lista()
        {
            if (HttpContext.Session.GetInt32("idUsuario") == null)
            {
                return RedirectToAction("Login", "Usuario");
            }
            MensagemBanco mens = new MensagemBanco();
            List<Mensagem> lista = mens.Query();
            return View(lista);
        }
        
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Login", "Usuario");
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Black Imóveis</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Black Imóveis</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mensagem" asp-action="FaleConosco">Contato</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Anuncio" asp-action="Cadastro">Anuncie Seu Imóvel</a>
                        </li>
                    </ul>
                </div>
            </div>
             @if(Context.Session.GetInt32("idUsuario") != null)
                {
                    <span>Olá, @Context.Session.GetString("nomeUsuario") - <a asp-action="Logout">Sair</a></span>
                }
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Black Imóveis - <address><a href="mailto:example.com">example@example.com</a></address>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>